# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='owner_id',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='room_id',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='rule',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='sheriff_id',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
