# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0002_auto_20161110_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='rule',
            field=models.IntegerField(default=1),
        ),
    ]
