# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0004_auto_20161110_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standings',
            name='result',
            field=models.CharField(default='true', max_length=10),
        ),
    ]
