# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0005_auto_20161110_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
