# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0006_auto_20161112_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='answer',
            field=models.CharField(default='\u73a9\u5bb6', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='question',
            field=models.CharField(default='\u6211\u7684\u540d\u5b57', max_length=200),
        ),
    ]
